update readme

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -3,19 +3,12 @@ name: Node.js CI
 on: [push, workflow_dispatch]
 
 jobs:
+
   build:
-
     runs-on: ubuntu-latest
-    continue-on-error: true
-
-    # strategy:
-    #   matrix:
-    #     node-version: [12.x]
-
-    steps:
     
+    steps:
       - uses: actions/checkout@v2
-      # - run: echo ::set-env name=FILENAME::ReadMeSquelette.md
 
       - run:  echo "version=1.0.1" > report_correction.txt
       - run:  echo GITHUB_REPOSITORY=$GITHUB_REPOSITORY > report_correction.txt
@@ -101,7 +94,7 @@ jobs:
         uses: ./.github/actions/text-exist
         with:
          filename: "test/jeu.test.ts"
-         text: 'expect(response.body.résultat.v3).toBeWithin(1, 7);'
+         text: 'expect(response.body.résultat.v3).toBeWithin(1, 7)'
          report: "report_correction.txt"
 
     
@@ -114,12 +107,6 @@ jobs:
           total_text_exist=$(( $nb_error + $nb_success ))
           percent_success=$(( $nb_success  / $total_text_exist )).$(( ($nb_success  * 100 / $total_text_exist) % 100 ))
           
-          echo "::set-output name=file_missing::$file_missing"
-          echo "::set-output name=nb_error::$nb_error"
-          echo "::set-output name=nb_success::$nb_success"
-          echo "::set-output name=total_text_exist::$total_text_exist"
-          echo "::set-output name=percent_success::percent_success"
-
           echo " " >> report_correction.txt
           echo "Text exist statistics" >> report_correction.txt
           echo "file_missing=$file_missing"  >> report_correction.txt
@@ -128,79 +115,97 @@ jobs:
           echo "total_text_exist=$total_text_exist" >> report_correction.txt
           echo "percent_success=$percent_success" >> report_correction.txt
 
-
       - name: Use Node.js ${{ matrix.node-version }}
         uses: actions/setup-node@v1
         with:
           node-version: ${{ matrix.node-version }}
+      
+      - uses: actions/checkout@v2
+      - run: npm install
+      - run: npm run build --if-present
+      - run: npm run testj || true
 
-      - run: |
-          npm install
-          npm run build --if-present
-          npm run testj > jest.json
-
-      - name: test stats
+      - name: TEST STATISTICS
         id: test_stats
         run: |
-          numPassedTests=$(grep -o '"numPassedTests":[0-9][0-9,\"][0-9,\"]' jest.json | tr -d ',' | tr -d '"') 
-          numPassedTests=${numPassedTests//'numPassedTests:'/}
-          numFailedTests=$(grep -o '"numFailedTests":[0-9][0-9,\"][0-9,\"]' jest.json | tr -d ',' | tr -d '"') 
-          numFailedTests=${numFailedTests//'numFailedTests:'/}
-          nb_total_test=$(( $numPassedTests + $numFailedTests ))
-          echo "::set-output name=nb_total_test::$nb_total_test"
-          echo "::set-output name=num_passed_tests::$numPassedTests"
-    
-          percent_test=$(( $numPassedTests / $nb_total_test ))     
+          if [ -f "jest.json" ]; then
+            numPassedTests=$(grep -o '"numPassedTests":[0-9][0-9,\"][0-9,\"]' jest.json | tr -d ',' | tr -d '"') 
+            numPassedTests=${numPassedTests//'numPassedTests:'/}
+            numFailedTests=$(grep -o '"numFailedTests":[0-9][0-9,\"][0-9,\"]' jest.json | tr -d ',' | tr -d '"') 
+            numFailedTests=${numFailedTests//'numFailedTests:'/}
+            nb_total_test=$(( $numPassedTests + $numFailedTests ))
+            percent_test=$(( $numPassedTests  / $nb_total_test )).$(( ($numPassedTests  * 100 / $nb_total_test ) % 100 ))
 
-          echo " " >> report_correction.txt
-          echo "test statistics" >> report_correction.txt 
-          echo "numPassedTests=$numPassedTests" >> report_correction.txt
-          echo "numFailedTests=$numFailedTests" >> report_correction.txt
-          echo "percent_test=$percent_test" >> report_correction.txt
+            echo " " >> report_correction.txt
+            echo "test statistics" >> report_correction.txt 
+            echo "numPassedTests=$numPassedTests" >> report_correction.txt
+            echo "numFailedTests=$numFailedTests" >> report_correction.txt
+            echo "nb_total_test=$nb_total_test" >> report_correction.txt
+            echo "percent_test=$percent_test" >> report_correction.txt
+          else
+            echo " " >> report_correction.txt
+            echo "test statistics" >> report_correction.txt 
+            echo "numPassedTests=0" >> report_correction.txt
+            echo "numFailedTests=0" >> report_correction.txt
+            echo "nb_total_test=0" >> report_correction.txt
+            echo "percent_test=0" >> report_correction.txt
+          fi
 
-      - name: Uncovered files
+
+      - name: UNCOVERED FILES BY TEST"
         id: uncovered
         run: |
-            uncovered_lines=$(sed -n "/<span class=\"strong\">/p" coverage/lcov-report/index.html | grep "100%" | wc -l)
-            echo "uncovered_lines=$uncovered_lines"
-            echo "::set-output name=lines::$uncovered_lines"
-            echo "::set-output name=total::4"
-            sed -n "/<span class=\"strong\">/p" coverage/lcov-report/index.html 
-
+          if [ -d "coverage" ] && [ -f "coverage/lcov-report/index.html" ]; then
+            coverage_info=$(sed -n "/<span class=\"strong\">/p" coverage/lcov-report/index.html)
+            full_coverage_info=$(echo $coverage_info | grep "100%" || true) 
+            echo "$full_coverage_info"
+            if [ -z "$full_coverage_info"]; then
+              uncovered_lines=0
+            else
+              uncovered_lines=$(sed -n "/<span class=\"strong\">/p" coverage/lcov-report/index.html | grep "100%" | wc -l )
+            fi
+           
             echo " " >> report_correction.txt
             echo "Uncovered info " >> report_correction.txt
             echo "uncovered_lines=$uncovered_lines" >> report_correction.txt
             sed -n "/<span class=\"strong\">/p" coverage/lcov-report/index.html  >> report_correction.txt
+          else
+            echo "Coverage report not generated because of test failure" >> report_correction.txt
+            echo "uncovered_lines=0" >> report_correction.txt
+          fi
 
-             
-      - run: |
-          nb_success=${{steps.statistics.outputs.nb_success}}
-          total_text_exist=${{steps.statistics.outputs.total_text_exist}}
+      - name: COMPUTE NOTES
+        run: |
+          nb_success=$(cat "report_correction.txt" | grep "nb_success" | awk 'BEGIN { FS = "=" } ; {print $2}' )
+          total_text_exist=$(cat "report_correction.txt" | grep "total_text_exist" | awk 'BEGIN { FS = "=" } ; {print $2}' )
 
-          num_passed_tests=${{steps.test_stats.outputs.num_passed_tests}}
-          nb_total_test=${{steps.test_stats.outputs.nb_total_test}}
+          numPassedTests=$(cat "report_correction.txt" | grep "numPassedTests" | awk 'BEGIN { FS = "=" } ; {print $2}' )
+          nb_total_test=$(cat "report_correction.txt" | grep "nb_total_test" | awk 'BEGIN { FS = "=" } ; {print $2}' )
+
         
-          uncovered_lines=${{steps.uncovered.outputs.lines}}
-          uncovered_lines_total=${{steps.uncovered.outputs.total}}
+          uncovered_lines=$(cat "report_correction.txt" | grep "uncovered_lines" | awk 'BEGIN { FS = "=" } ; {print $2}' )
+          uncovered_lines_total=4
           
+          # echo "nb_success=$nb_success, total_text_exist=$total_text_exist , numPassedTests=$numPassedTests,  nb_total_test=$nb_total_test ,uncovered_lines=$uncovered_lines, uncovered_lines_total=$uncovered_lines_total "
+
           total=$(( $total_text_exist + $nb_total_test + $uncovered_lines_total ))
-          pass=$(( $nb_success + $num_passed_tests + $uncovered_lines))
+          pass=$(( $nb_success + $numPassedTests + $uncovered_lines ))
           note=$(( $pass  / $total )).$(( ($pass  * 100 / $total ) % 100 ))
             
-          echo " " 
+          echo " " >> report_correction.txt
           echo "Statistiques finales "  >> report_correction.txt
           echo "total=$total" >> report_correction.txt
           echo "pass=$pass" >> report_correction.txt
           echo "note finale=$note"  >> report_correction.txt
           
-      - name: get Student name
+      - name: GET STUDENT NAME
         run: |
             student_name=$(sed -n '/studentName/p' README.md | sed  's:</studentName>:\'$'\n'':g'  | sed -n 's/.*>//p')
             echo "student_name=$student_name" >> report_correction.txt
 
       - run: cat report_correction.txt
 
-      - name: Commit report
+      - name: COMMIT REPORT
         run: |
           git config --global user.name 'Yvan Ross'
           git config --global user.email 'yvan.ross@gmail.com'
@@ -208,12 +213,12 @@ jobs:
           git commit -am "Automated report generated by Yvan Ross"
           git push
 
-      - name: upload report_correction.txt
+      - name: UPLOAD report_correction.txt
         uses: actions/upload-artifact@v2
         with: 
           name: reports
           path: report_*.txt
-
+      
 
     env:
         CI: true
